jupiter deployment fixes due to canonical url (#157)
* jupiter deployment fixes due to canonical url

* fixes to url contetxt

* fixes to redirect issues in deployment

* fix indentetion issue

* Fix workflow and redirect logic with updated page.html

diff --git a/.github/workflows/pages.yml b/.github/workflows/pages.yml
--- a/.github/workflows/pages.yml
+++ b/.github/workflows/pages.yml
@@ -1,11 +1,9 @@
-# see https://github.com/actions/starter-workflows/blob/main/pages/jekyll.yml
 name: site
 on:
   push: {branches: [main], tags-ignore: ['**']}
   pull_request:
   schedule: [{cron: '0 10 * * 6'}]  # M H d m w (Sat 10:00)
 permissions:
-  # allow GITHUB_TOKEN to deploy to GitHub Pages
   contents: read
   pages: write
   id-token: write
@@ -21,7 +19,7 @@ jobs:
     - uses: actions/setup-python@v4
       with: {python-version: '3.11'}
     - run: pip install -r requirements.txt pyyaml
-    - name: check CITATION.cff & .zenodo.json
+    - name: Check CITATION.cff & .zenodo.json
       run: |
         python <<EOF
         import json, yaml
@@ -49,13 +47,17 @@ jobs:
     - id: pages
       uses: actions/configure-pages@v3
     - run: pip install -r requirements.txt
-    - name: jupyter-book build
+    - name: Verify `page.html` Exists
+      run: |
+        if [ ! -f _templates/page.html ]; then
+          echo "Error: _templates/page.html not found!"
+          exit 1
+        fi
+    - name: Build Jupyter Book
       run: |
         sudo apt update -qq
-        sudo apt install -qq ghostscript fonts-freefont-otf  # https://stackoverflow.com/a/69012150
-        sed -ri 's#^(\s*baseurl:).*#\1 ${{ steps.pages.outputs.base_url }}/'$SITE_PREFIX'#g' _config.yml
+        sudo apt install -qq ghostscript fonts-freefont-otf
         jupyter-book build --builder dirhtml --warningiserror --nitpick --keep-going .
-        # fix https://github.com/executablebooks/jupyter-book/issues/2066
         sed -ri 's#(.*link rel="canonical" href=".*)\.html(".*)#\1/\2#' _build/dirhtml/*/index.html
     - uses: xu-cheng/latex-action@v3
       with:
@@ -66,11 +68,11 @@ jobs:
       env:
         XINDYOPTS: -L english -C utf8 -M sphinx.xdy
       continue-on-error: true
-    - name: prepare _site pages
+    - name: Prepare `_site` for Pages Deployment
       run: |
         mkdir _site
         mv _build/dirhtml _site/$SITE_PREFIX
-        sed "s#DESTINATION#${{ steps.pages.outputs.base_url }}/$SITE_PREFIX#g" .redirect-template.html > _site/index.html
+        sed "s#DESTINATION#https://book.premai.io/$SITE_PREFIX#g" _templates/page.html > _site/index.html
     - uses: actions/upload-pages-artifact@v2
   deploy:
     if: github.ref == 'refs/heads/main'
